### ISSUE TITLE
Add Button component files in a folder

### ISSUE THREAD

**Issue by damdiana** [damdiana/beauty-app#5]

**Comment by iampava** [comment]
I don't understand this issue. Can you explain what's the intention?

**Comment by damdiana** [comment]
I created a 'components' folder and within, I created a Button.css, Button.tsx and Button.stories.tsx, without creating a Button folder

**Comment by iampava** [comment]
Got it. Feel free to commit this directly to `main` without waiting for approval

**Comment by damdiana** [comment]
Thanks! Will do
